#!/bin/bash

# Returns a '#' if the shell is running with privileges, a '$' if not
prompt_priviliges_info() {
  echo $'%(!.#.$)'
}

# Returns the shortened path to the current directory : '~/…/c/d'
prompt_dir_info() {
  echo $'%(4~|%-1~/…/%2~|%3~)'
}

setup() {
  setopt prompt_subst

  RPROMPT='[right part of me]'
  PROMPT=$'%K{153}$(prompt_dir_info)%k%F{153}\ue0b0%f$(prompt_priviliges_info) '
}

setup "$@"
